spring.application.name=jo_tech_hub

# jjwt requires 32 character long or 256 bytes
jwt.secret = helloMyNameIsDizasterAndIAmGonnaDoMoreThan32Characters1111111111111

# MySQL Database

spring.datasource.url=jdbc:mysql://localhost:3306/abdullah_app?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=berlin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
